### PR TITLE
Relocate drafts

### PR DESCRIPTION
**Pull request by pauljmartinez**
Move drafts to a more Jekyll-centric location.

### CODE REVIEW

**Comment by randybias** [comment]
We should probably curate before we relocate.

**Comment by pauljmartinez** [comment]
I don't think this relocation will effect curation.

**Comment by randybias** [comment]
Could happen later, I guess.  It's just handy that they are in one place at
the moment...

**Comment by randybias** [comment]
In fact, I can't tell what some of these are.  Some look like actually blog postings, but perhaps they were earlier WP revisions that are still tagged drafts?  Can we confirm that they are dupes and then really these should perhaps all be deleted.

**Comment by pauljmartinez** [comment]
Hi Randy, these are dupes or drafts of posts never published, or perhaps reworked into something else.

**Comment by randybias** [comment]
Then they should be deleted.

**Pull request closed without merging**
