### PR TITLE
Add images from Ceph and update path to use local images - fix missin…

### PR DESCRIPTION
**Pull request by zdevil**
…g images

### CODE REVIEW

**Comment by randybias** [comment]
Still missing this?

http://ceph.com/docs/dumpling/_images/stack.png

**Comment by zdevil** [comment]
Hi Randy,

I added it here
https://github.com/randybias/cloudscaling.com/blob/master/assets/media/2015/08/stack.png

Thanks

## Hamza Essaoui

Flickerbox, Inc.
735 Bryant Street
San Francisco, CA 94107
(415) 436-9383 Office
(415) 276-1866 Fax

**Comment by randybias** [comment]
Nevermind.  Have to clear the cache.  My bad.

**Comment by zdevil** [comment]
No worries.

Thanks

## Hamza Essaoui

Flickerbox, Inc.
735 Bryant Street
San Francisco, CA 94107
(415) 436-9383 Office
(415) 276-1866 Fax

**Pull request merged**
