### PR TITLE
PR to review engineering posts

### PR DESCRIPTION
**Pull request by pauljmartinez**
This PR is not ready to be pushed live. It needs to be reviewed first.

If these posts look ok, we still need to:
- Confirm new URLs for these posts
- Add appropriate redirects to engineering blog
- Remove blog/_posts/2016-06-21-checklist.markdown

### CODE REVIEW

**Comment by pauljmartinez** [comment]
There are two missing images for the vlan post, these are the old urls, do you have access to these?

https://lh5.googleusercontent.com/gcSxxhkydQWexbIIHhj63YFH9BpKo_FfMVVzwNZpACGP2VykvMXmHWy0NXYr1zcxxb29jiRodhdvPrl2CIPwBYm8GuZ3qHtZ4KYxtKW3yXGuWuoYGPE0giU

https://lh3.googleusercontent.com/ug5N66HO_75wuMgADh9F7C8I-E1gWz_fojyE-me2DvOSeiXLZdj-JDk0T-2fP3TQxq6sGmeDiTMvbsLPm7JMfUQ5RdTfXyXWgQ5h7QZS4_ImaffuyP5NEFs

**Comment by randybias** [comment]
Yeah.  I shared that GDoc folder to you already with the original posts.
You can save them to disk from there.

**Comment by randybias** [comment]
Where are we at with this one?

**Comment by pauljmartinez** [comment]
Hi Randy, Could you please add paul@flickerbox.com to the Google Docs folder with the original posts?

**Comment by randybias** [comment]
I believe I shared the entire folder with you now.

**Pull request closed without merging**
